### ISSUE TITLE
Could this algorithm be used in Mouse data?

### ISSUE THREAD

**Issue by RinconFer** [cortes-ciriano-lab/SComatic#12]
Hello,
I work with cancer mouse models using both scRNAseq and snATACseq datasets, I would like to use this package to detect mutations in my cancer models. Is it possible to use it in Mouse datasets?

**Comment by Francesc-Muyas** [comment]
Dear user,
Thanks for your interest in SComatic. Our algorithm can be run in different types of species; however, there are a few limitations that need to be in consideration. 

1. SComatic has been benchmarked using Human data, so although we do not find many reasons for having worse performance, we cannot guarantee the same performance for mice or other species.
2. As you will realise, step 4 of SComatic takes (**not mandatory, but recommended**) a Panel of Normals (PoN) for filtering potential germline and systematic error contamination. In the repo (as described in the manuscript), we provide a scRNA-seq PoN for the human genome. **However, although we don't have the PoN for the mouse genome ready yet,  we are working on it and hope it will be available in the Github repo soon**.
3. Similar to the previous point, step 4 of SComatic also takes (**not mandatory, but recommended, and only for scRNA-seq data**) an RNA-editing bed file with positions known to be affected by A-to-I and/or C-to-U editing events in the literature. **Although the one provided in the repo is based on the human genome, we are collapsing some mouse RNA-editing databases and will upload this file to the GitHub repo soon**.

You'll find these updates in the GitHub repo soon!
Thanks for your interest, 
Fran

**Comment by RinconFer** [comment]
Thank you very much!

I'll wait then for the mouse PoN and the bed file.

Best,
David

**Comment by Francesc-Muyas** [comment]
Just to let you know. We are working on it and expect to deliver these files next week.

**Comment by RinconFer** [comment]
That's great! Thank you! Once you upload it  I'll give it a try as soon as I can and let you know how it went

**Comment by Francesc-Muyas** [comment]
Dear user, 
Sorry for the delay. We have now generated and uploaded the files we promised. They have been computed using the [_Tabula Muris Senis data_](https://tabula-muris-senis.ds.czbiohub.org/), so please cite them as well when using these files. 

You will find both the mm10 PoN and RNA-editing files in the [PoN](https://github.com/cortes-ciriano-lab/SComatic/tree/main/PoNs) and [RNA-editing](https://github.com/cortes-ciriano-lab/SComatic/tree/main/RNAediting) folders, respectively. 

Thanks for your patience,
Fran
