### ISSUE TITLE
Application to Smart-seq2

### ISSUE THREAD

**Issue by LiQian-XC** [cortes-ciriano-lab/SComatic#13]
Hi Francesc,

Thanks for this useful tool. When applying SComatic to single-cell data from Smart-seq2, are the beta-binomial parameters needed to be adjusted/re-inferred using a panel of unrelated samples from Smart-seq2? If yes, can you recommend which samples to use for estimating these parameters, especially when I want to call somatic mutations from normal samples/tissues? Similarly, is PON also needed to be customised?

Thank you in advance!

Best,
Qian

**Comment by yuhsinhsieh-josch** [comment]
Hi Francesc,

I have similar question, but would like to use SComatic for scATAC from 10X genomic.

Thank you!

Best,
Yu-Hisn

**Comment by Francesc-Muyas** [comment]
Dear users, 

Thanks for bringing up this interesting point about the Smart-seq2 data. Unfortunately, we have not tested our tool with such data, but I do not see the reason (as far as they have the CB information in the bam) for not being ready for SComatic.

As you have mentioned, it would be better to re-estimate the Beta-Binomial with tumour-free samples, where we should expect a low number of true somatic mutations. If you cannot find enough samples (5-10) to be used in this step, I would suggest going ahead with the scRNA-seq parameters, but (for sanity check) I would increase the _--min_ac_cells_ parameter in Step 4.1 to 3 ( _--min_ac_cells 3_). In addition, the ideal situation would be that you re-construct your own PoNs with you multiple samples. Nevertheless, we know that this is not always possible. If this is the case, you could use the alternative PoNs described in [Step 4.2](https://github.com/cortes-ciriano-lab/SComatic#step-42). 

Regarding the scATAC-seq data, you quite be quite confident using the default Beta-Binomial parameters in SComatic, as well as the scATAC-seq PoN in this repository. However, you can use other PoNs alternatives (e.g. provided by GATK).

Thanks, 
Fran
