### ISSUE TITLE
Warning for R package installation

### ISSUE THREAD

**Issue by gangcai** [cortes-ciriano-lab/SComatic#14]
`$ Rscript r_requirements_install.R`

Warning message:
package ‘VGAM’ is not available (for R version 3.6.1)

**Comment by Francesc-Muyas** [comment]
Dear user, 
Could you please try to do this in R? 

```
package_url <- "https://cran.r-project.org/src/contrib/Archive/VGAM/VGAM_1.1-7.tar.gz"
install.packages(package_url, repos=NULL, type="source")
```

In any case, R (and this package) is only used in the [BetaBinEstimation.py](https://github.com/cortes-ciriano-lab/SComatic/blob/main/scripts/BetaBinEstimation/BetaBinEstimation.py) script, so unless you need this step for re-calculating the Beta-binomial parameters, you can go ahead with your analysis. 

Cheers,
Fran

**Comment by gangcai** [comment]
Thanks for the reply. Above solution works for R 3.6.1. Since current VGAM requires R >=4.0.0, maybe it's better to recommend installation of this version of R at the very beginning.

**Comment by vladimirkovacevic** [comment]
I'm still getting the same error which is being solved but the suggestion given here. You may consider updating r_requiremens file accordingly. Thanks!
