### ISSUE TITLE
AttributeError: 'pysam.calignedsegment.PileupColumn' object has no attribute 'get_num_aligned' is occurred in step2

### ISSUE THREAD

**Issue by yasuhikohaga** [cortes-ciriano-lab/SComatic#18]
Thank you for great tool.

I am running snRNA-seq data and AttributeError: 'pysam.calignedsegment.PileupColumn' object has no attribute 'get_num_aligned' is occurred in step 2 :  Collecting base count information.

I just changed path from example code and run like this 

python $SCOMATIC/scripts/BaseCellCounter/BaseCellCounter.py --bam $bam \
    --ref $REF \
    --chrom all \
    --out_folder $SCOMATIC/data_haga/PC9_1/Step2_BaseCellCounts \
    --min_bq 30 \
    --tmp_dir $temp \
    --nprocs 1

and got an error like this

Traceback (most recent call last):
  File "SCOMATIC/scripts/BaseCellCounter/BaseCellCounter.py", line 410, in <module> main()
  File "SCOMATIC/scripts/BaseCellCounter/BaseCellCounter.py", line 402, in main
    collect_result(run_interval(row, BAM, FASTA, MIN_COV, MIN_CC, MIN_AF, MIN_AC,tmp_dir, MIN_BQ, MIN_MQ))
  File "SCOMATIC/scripts/BaseCellCounter/BaseCellCounter.py", line 202, in run_interval
    DP = p.get_num_aligned()
AttributeError: 'pysam.calignedsegment.PileupColumn' object has no attribute 'get_num_aligned'

pysam version is 0.16.0.1, and should I change pysam version? or is there any solution?

Best regards,

Yasu

**Comment by Francesc-Muyas** [comment]
Dear user, 
Thanks for bringing this up. Could you let me know if you managed to run the example sample?

Cheers,
Fran

**Comment by yasuhikohaga** [comment]
Thanks for your reply and sorry for my late response.

I got same error even running example sample.

version of my tools are shown under here
# Name                    Version                   Build  Channel
about-time                3.1.1                    pypi_0    pypi
numpy                     1.21.6                   pypi_0    pypi
numpy-groupies            0.9.14                   pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
pybedtools                0.8.1            py37he513fc3_0    bioconda
pysam                     0.16.0.1                 pypi_0    pypi
rpy2                      2.9.4           py37r36hd767a1f_3    conda-forge
scipy                     1.7.3                    pypi_0    pypi

pybedtools and rpy2 were installed by conda because these couldn't be installed by pip in my environment.

best regards,
Yasu

**Comment by evelyn-schmidt** [comment]
Hello all,

I just tried running the test data today and am getting the same issue. My version of pysam is 0.9.1 and was installed with bioconda. 

thanks,
Evelyn

**Comment by Francesc-Muyas** [comment]
Dear users, 
It seems to be a problem with the pysam package. Could you try to install _pysam_ using conda as well, and let me know if can run the example?

Cheers,
Fran

**Comment by Renty9** [comment]
> Dear users, It seems to be a problem with the pysam package. Could you try to install _pysam_ using conda instead, and let me know if can run the example?
> 
> Cheers, Fran

It works with all versions of pysam. And I  run the example successfully. I think the reason for the error is that the wrong reference sequence was used

**Comment by Francesc-Muyas** [comment]
Hi people! 
A couple of questions:

1. Are you running SComatic in a Linux env?
2. Could you try, for instance, this pysam version (pysam==0.16.0.1)? 
3. Could you paste the command line you are using? 

Cheers,
Fran

**Comment by LASeeker** [comment]
Hello everyone, 
I got the same error with both my data and the provided example data (thank you! Very helpful to have it!). 
I de-installed Pysam and installed its most recent version (0.22.0) with pip and now it works with both the example dataset and my own. 
Cheers, 
Luise
