### ISSUE TITLE
SComatic on Stereo-seq data

### ISSUE THREAD

**Issue by vladimirkovacevic** [cortes-ciriano-lab/SComatic#21]
Thank you for very well-written paper and great documentation! 
I was wondering would it make sense to run SComatic on [Stereo-seq](https://www.cell.com/cell/pdf/S0092-8674(22)00399-3.pdf) spatial transcriptomics data. In essence, the main difference with single cell data is lower gene resolution (not all genes are available for all cells, but only a random subset of genes)?
If yes, which method would you recommend for adding CB to BAM tag? I suppose pysam, that walks through every read, but it might be too slow. Also, about tags for number of hits and number of misses, which tool would you recommend for calculating it?

**Comment by Francesc-Muyas** [comment]
Dear user, 
Thanks for your interest in SComatic. Regarding the CB, is it located in the read name? I think pysam is a fast and good solution that should not take more than a few minutes to run, but it depends on the way of linking the read to the CB, as well as the number of total reads.

Secondly, how did you align the bam file? 

Thanks for your time, 
Fran

**Comment by vladimirkovacevic** [comment]
Read names have information about spot, but dozens of spots are merged into cell due to large spatial resolution of Stereo-seq of 500nm. But I have external info that I can use to decode and impute into BAM tags.
We use STAR aligner, just noticed that number of hits and misses are already there! Thanks!
