### ISSUE TITLE
Run SComatic with a matched normal single-cell RNA-seq data

### ISSUE THREAD

**Issue by gongyuTang123** [cortes-ciriano-lab/SComatic#22]
I am trying to detect somatic mutations from my single-cell RNA-seq data for lung cancer samples. I knew SComatic relies on different cell types' data to remove possible germline mutations and artifacts. But I happened to have the matched normal single-cell data isolated from the same cancer patient. How could these data be used to help generate better results by SComatic?

Should I use the 'scripts/PoN/PoN.py' to generate a novel PON for each patient or for each cell subpopulation and use it as a reference to remove possible germline mutations?

**Comment by Francesc-Muyas** [comment]
Dear user, 
Sorry for not getting back to you sooner. The question that you bring is quite interesting and can have different ways of being approached: 

1. You should first run the full SComatic workflow in the normal sample. Next, take the **unfiltered** output of the  [Step4.2](https://github.com/cortes-ciriano-lab/SComatic#step-42) of this matched normal sample and used it as `--pon` in the [Step4.2](https://github.com/cortes-ciriano-lab/SComatic#step-42) of the tumour sample. 
2. Alternatively, compute the [PoN script](https://github.com/cortes-ciriano-lab/SComatic/blob/main/docs/pon.md#panel-of-normals-pon) using the _basecalling.step1.tsv_ file obtained for the normal sample and set the parameter `--min_samples 1`. You can then use this PoN for the tumour sample. 

I hope it helps, 
Fran
