### ISSUE TITLE
How SComatic distinguishes between somatic and germline variants?

### ISSUE THREAD

**Issue by vladimirkovacevic** [cortes-ciriano-lab/SComatic#24]
I managed to run SComatic on mouse colorectal cancer of Stereo-seq data. On the 4th step data for all sites is obtained and I assume the [variants](https://pasteboard.co/Z3kJntFxg1BB.png) could be among locations marked with Multiple_cell_type in the FILTER column. But there are too many of them and ALT alleles on all cell types are the same. Also, all variants are marked with PASS in Cell_type_Filter column. Does SComatic provide the list variants marked strictly as somatic?
One more question, is creation of PoN necessary to mark variant as somatic?

**Comment by Francesc-Muyas** [comment]
Dear user, 
Thanks for using SComatic. 

To get the high-quality somatic variants, **you ONLY should take the variants marked as _PASS_ in the _FILTER_ column**. The cell type harbouring these variants should be specified in the column _Cell_types_. 

Ignore the _Cell_type_Filter_ column, as it only shows the PASS or not PASS labels for the Beta-binomial test at single cell type resolution (first step of the variant calling), and not the cell type comparison or other hard filters. 

The PoN is not 100% mandatory to run SComatic, but is recommended to remove artefacts or germline contamination. If you don't have it available for your data, you could use as PoN file an unzipped vcf with the germline variants found in the mouse population (for example, variants found in your mouse strain). Alternatively, you can find a PoN for the mm10 genome (only 10X scRNA-seq data). Unfortunately, we do not have a PoN for Stereo-seq data. 

Thanks, 
Fran

**Comment by vladimirkovacevic** [comment]
Yes, thank you @Francesc-Muyas! This is what I was looking for. Now the PASS variants by VAF value look like somatic variants, altho [some of them ](https://pasteboard.co/uSu12hyF7wMV.png)have strange VAF such as 0.5 or 0.67. I saw the hardcoded threshold of 0.15 in 4th step (variant calling). What do you think?

**Comment by Francesc-Muyas** [comment]
Hi,

Variants with VAFs around ~0.5 do not need to be germline variants, especially if you find them in **ONLY one** of the cell types with expression for a given position (at least expression in two cell types). For example, they can be clonal mutations or be the result of allelic dropout.

Please, consider using the PoN as suggested in the previous comments, or simply remove the variant sites with known germline variants in the mouse strain you are working with.

Cheers, 
Fran
