### ISSUE TITLE
package ‘VGAM’ is not available (for R version 3.6.1)

### ISSUE THREAD

**Issue by FionaMoon** [cortes-ciriano-lab/SComatic#25]
Hi all,
I can't install the dependency 'VAGM' .
How can I solve this problem?

**Comment by Francesc-Muyas** [comment]
Dear user, 
Could you please try to do this in R? 

```
package_url <- "https://cran.r-project.org/src/contrib/Archive/VGAM/VGAM_1.1-7.tar.gz"
install.packages(package_url, repos=NULL, type="source")
```

In any case, R (and this package) is only used in the [BetaBinEstimation.py](https://github.com/cortes-ciriano-lab/SComatic/blob/main/scripts/BetaBinEstimation/BetaBinEstimation.py) script, so unless you need this step for re-calculating the Beta-binomial parameters, you can go ahead with your analysis. 

Cheers,
Fran
