### ISSUE TITLE
Can you run SComatic on bulk RNA seq?

### ISSUE THREAD

**Issue by sph17** [cortes-ciriano-lab/SComatic#26]
Hi,

I was wondering if SComatic could be used to run on bulk RNA seq data?

Thanks,
Steph

**Comment by Francesc-Muyas** [comment]
Dear user, 
SComatic is a tool designed to be used with single-cell data, and cannot be run on bulk RNA-seq data. The main reason for that is that SComatic looks for the CB (cell barcode) tag in the bam file to get the base counts, which will be used for the next steps of the algorithm to get somatic calls. 

Cheers,
Fran
