### ISSUE TITLE
chromosome name difference, e.g., chr1 vs 1

### ISSUE THREAD

**Issue by robinycfang** [cortes-ciriano-lab/SComatic#27]
Hi,

My scRNA-seq data were aligned using fasta file without "chr", so it looks like this:

`D00353:300:HNLF3BCX2:2:2116:12760:71863 256     1       11201   0       98M     *       0       0       GCTTGCTCACGGTGCTGTGCCAGGGCGCCCCCTGCTGGCGACTAGGGCAACTGCAGGGCTCTCTTGCTTAGACTGGTGGCCAGCGCCCCCTGCTGGCG       DCCDCIIIIHIHI@HHEHEEHHFHGHHHCDECHEHGIIDDFIHIIHHGIHIIHHIIIHHHHGHIFIIIIIIHIHHEHGHHHHHF?EHHDHDHHHEFH?      NH:i:5  HI:i:2  AS:i:94 nM:i:1  RE:A:I  li:i:0  BC:Z:CTGCAAGC    QT:Z:DDDDDIII   CR:Z:TATCTCAAGATGCGAC   CY:Z:DDDDDGHIIIIIIIHI   CB:Z:TATCTCAAGATGCGAC-1 UR:Z:ATTCTACATG UY:Z:IGIIIIIIHI UB:Z:ATTCTACATG RG:Z:T_100070:0:1:HNLF3BCX2:2`

However, I am worried that due to the difference in "chr", when you apply files of PoN and editting sites which have "chr" in the names, these filters might actully not work as the CHROM is different. In your program, does it convert between differenct chromosome names? If the name doesn't automatically convert in the program, it would be good to add such feature, as realign the reads to another version of fasta would be time-consuming.

Thanks.

**Comment by Francesc-Muyas** [comment]
Dear user, 
Thanks for bringing up this topic. For now, the tool does not recognise if the chromosomes have prefix or not. So you have to use the same Hg38 with a prefix in the chromosomes. We might include this update in the future. 

In any case, we are preparing (and soon updating) the _PoN_ and _Editing_ files without the "chr" prefix to allow the users to use the one they prefer. 

Cheers,
Fran

**Comment by Francesc-Muyas** [comment]
These files have been added to the [PoNs](https://github.com/cortes-ciriano-lab/SComatic/tree/main/PoNs) folder. 

Thanks, 
Fran
