### ISSUE TITLE
How to convert to standard vcf format to be used  for downstream analyses?

### ISSUE THREAD

**Issue by lipika487** [cortes-ciriano-lab/SComatic#32]
Hi, thanks for the amazing tool.
I successfully ran the Scomatic pipeline, output I have is in .tsv format ( which somehow is looking like vcf format). But, how can I convert it into standard vcf format (as used by many other downstream analyses tools). 

I tried to convert it using vcf2vcf.pl from vcftools, but no success.

Thanks,
Lipika

**Comment by Francesc-Muyas** [comment]
Dear user, 

We do not provide one functionality for getting a _vcf_ format. However, in our manuscript, we have annotated these variants using _Annovar_. Please find in the [FAQs section](https://github.com/cortes-ciriano-lab/SComatic/blob/main/docs/faqs.md#2-how-can-we-perform-the-variant-annotation-with-the-scomatic-output) an easy way to do it. 

Thanks, 
Fran
