### ISSUE TITLE
TrinucleotideContextBackground.py -  No such file or directory!

### ISSUE THREAD

**Issue by lipika487** [cortes-ciriano-lab/SComatic#33]
Hi,
I was trying to use the TrinucleotideContextBackground.py. This is ss of my final output file after step 4.2.
<img width="960" alt="image" src="https://github.com/cortes-ciriano-lab/SComatic/assets/84702870/fa2bfbda-65e5-4e5d-868d-940f6906f56e">

This is error while I am using it. This just goes on for a long time.
<img width="960" alt="image" src="https://github.com/cortes-ciriano-lab/SComatic/assets/84702870/159440bb-67ff-4abf-a43b-08e999cc8344">

Am I doing it wrong or there is some other issue?

Thanks, 
Lipika

**Comment by Francesc-Muyas** [comment]
Dear user, 
This script requires the user to pass a file listing a the tsv files obtained in [step 4.1 ](https://github.com/cortes-ciriano-lab/SComatic#step-4-detection-of-somatic-mutations) (not 4.2). It can be run with one file or with multiple (especially if they are generated in a similar manner). 

Example of the input file:
```
Donor1.calling.step1.tsv
Donor2.calling.step1.tsv
Donor3.calling.step1.tsv
```

We apologise for not specifying this in the repo, as this is a very advanced functionality for a very limited number of people. In any case, we have now provided this info [here](https://github.com/cortes-ciriano-lab/SComatic/blob/main/docs/OtherFunctionalities.md#computing-the-trinucleotide-context-background). 

**Importantly**, and in general terms, all scripts provided in SComatic have the `--help` parameter to find the specific documentation of each functionality. So, if you have doubts, you can always run `python script_of_interest.py --help` to get the documentation of each script. 

Thanks, 
Fran

**Comment by lipika487** [comment]
Hi Fran, 
Thank you so much for a detailed explanation. It is working now. I am getting the output.

But it is not estimating the frequency of trinucleotides in my case.
<img width="214" alt="image" src="https://github.com/cortes-ciriano-lab/SComatic/assets/84702870/3b1dba5e-88e3-413d-92ae-fc3661fd4bfe">
Any idea why is it so?

Thanks, 
Lipika

**Comment by Francesc-Muyas** [comment]
Could you print the first lines of the tsv file (step4.1) you use?

**Comment by lipika487** [comment]
Yes, here you go.
<img width="960" alt="image" src="https://github.com/cortes-ciriano-lab/SComatic/assets/84702870/976c1edc-0e48-4144-8d27-95e5c020ff68">

**Comment by Francesc-Muyas** [comment]
What do you get if you run this? 

`grep -v '^#\|LC_' your.tsv | awk -F'\t' -v OFS='\t' '{if ($19 >= 2 && $20 >= 2) {print $0}}'`

**Comment by lipika487** [comment]
<img width="949" alt="image" src="https://github.com/cortes-ciriano-lab/SComatic/assets/84702870/77f24334-bf37-4402-96d6-ac8be66648f5">

**Comment by Francesc-Muyas** [comment]
Ok! Let's check the next:

And what about this?

`grep -v '^#\|LC_' your.tsv | awk -F'\t' -v OFS='\t' '{if ($19 >= 2 && $20 >= 2) {print $4,$8,$9}}'; done | sort -T $PWD | uniq -c | sed 's/^[ \t]*//' | tr ' ' '\t'`

**Comment by lipika487** [comment]
Giving syntax error.
<img width="945" alt="image" src="https://github.com/cortes-ciriano-lab/SComatic/assets/84702870/f3bb6de6-5b7f-4c3e-8e73-86bd11ad87b3">

**Comment by Francesc-Muyas** [comment]
During the computation, there should be created a *temp file. Could you paste it here?

**Comment by lipika487** [comment]
<img width="915" alt="image" src="https://github.com/cortes-ciriano-lab/SComatic/assets/84702870/0e3cd69b-6125-4130-b9a8-17c1542c8a6f">
Its empty.

**Comment by Francesc-Muyas** [comment]
Ok, let me try a couple of tests and I will come back to you soon.

**Comment by Francesc-Muyas** [comment]
The script is working in my example data. Could you try to run it using the example data as well? I put the command at the end of the [example documentation](https://github.com/cortes-ciriano-lab/SComatic/blob/main/docs/SComaticExample.md#computing-the-trinucleotide-context-background)

**Comment by lipika487** [comment]
Yes, I tried with Example data, its working perfectly with it.
But why not with my data, because all other steps are working fine?

**Comment by lipika487** [comment]
Done

**Comment by Francesc-Muyas** [comment]
The problem has been solved. This script was required to provide the full path for the output file. Now it has been updated to allow a short path output file.

**Comment by jgarces02** [comment]
I have the same problem. Were you able to solve it?

I think (at least in my case) it's something related to the file generated in the somatic calling process. It has a structure that doesn't fit `awk` commands in `TrinucleotideContextBackground.py`

```
(SComatic) [garcesj@jb21] ~/software/SComatic/tests · head Sample.CD14.monos_BL.tsv
##fileDate=12/03/2024
##INFO=DP,Description="Depth of coverage">
##INFO=NC,Description="Number of different cells">
##INFO=CC,Description="Cell counts [A:C:T:G:I:D:N:O], where D means deletion, I insertion and O other type of character">
##INFO=BC,Description="Base counts [A:C:T:G:I:D:N:O], where D means deletion, I insertion and O other type of character">
##INFO=BQ,Description="Base quality sums [A:C:T:G:I:D:N:O], where D means deletion, I insertion and O other type of character">
##INFO=BCf,Description="Base counts in forward reads [A:C:T:G:I:D:N:O], where D means deletion, I insertion and O other type of character">
##INFO=BCr,Description="Base counts in reverse reads [A:C:T:G:I:D:N:O], where D means deletion, I insertion and O other type of character">
#CHROM  POS     REF     INFO    Sample.CD14.monos_BL
GL000219.1      78864   A       DP|NC|CC|BC|BQ|BCf|BCr  6|5|5:0:0:0:0:0|6:0:0:0:0:0|222:0:0:0:0:0|0:0:0:0:0:0|6:0:0:0:0:0
GL000219.1      78864   A       DP|NC|CC|BC|BQ|BCf|BCr  6|5|5:0:0:0:0:0|6:0:0:0:0:0|222:0:0:0:0:0|0:0:0:0:0:0|6:0:0:0:0:0
GL000219.1      78865   A       DP|NC|CC|BC|BQ|BCf|BCr  6|5|5:0:0:0:0:0|6:0:0:0:0:0|205:0:0:0:0:0|0:0:0:0:0:0|6:0:0:0:0:0
```

When trying the internal `TrinucleotideContextBackground.py` `grep -v '^#\|LC_' Sample.CD14.monos_BL.tsv | awk -F'\t' -v OFS='\t' '{if ($19 >= 2 && $20 >= 2) {print $4,$8,$9}}'`, it only takes the _INFO_ field and does not populate the temporal file.

Thanks.

**Comment by BoLu68** [comment]
Hi @Francesc-Muyas,
I have some confusion regarding the logic in your script "TrinucleotideContextBackground.py":
"if REF in expected_bases:
             trincucleotide = ''.join(TRINUCLEOTIDE)
else:
             TRINUCLEOTIDE2 = [complemetary_dictionary[x] for x in TRINUCLEOTIDE]
             trincucleotide = ''.join(TRINUCLEOTIDE2)
"
This implies the code converts "AAG" to "TTC“.

However, "AAG" should be converted to "CTT". Is my understanding correct?
