### ISSUE TITLE
Challenges with adapting for long read data?

### ISSUE THREAD

**Issue by tsa4002** [cortes-ciriano-lab/SComatic#38]
Hi, 

I'm trying to run SComatic on long read data given the prevalence of variants to be within intronic regions and long read sequencing is better suited to capture those regions. 

What are the aspects of long read sequencing that make it difficult for use in de novo unpaired variant calling?

I have an aligned bam file from the PacBio Mas-Isoseq workflow. This is what an example read looks like 

`molecule/13430463	16	chr1	28288	0	82M1I219M	*	0	0	GACTTATTTGTGAAACCTTAGTATATATAAAAGTAGTTTCAAAGTTGCTAACATGTATTGCTGTGGGAAACAATTTTACCAATTTGGAGTTTAGTGCTTAGATATGCAGAGTTATTTGATTCTTTCCAGAATCTAATCAAAACACTGTTTTTGGACTTACCCAGGTCAGCTCCTTTCTGCCCACTCTTTCAGCGCAGGCGTGTCCTGCTGTGGAACACACTCTGGGATTCCTGTGTGGGTCTGTACCCATCCTGTACCCGTCAGGACCCCCAGGCCCCAACTCTTGATGTTGTTCTTGCTCC	BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB	NM:i:4	ms:i:279	AS:i:279	nn:i:0	ts:A:+	tp:A:P	cm:i:86	s1:i:288	s2:i:288	de:f:0.0132	MD:Z:270G5T0G23	rl:i:0	  CB:Z:ATACGGTTGTAGACCT	XA:Z:XM-CB	XM:Z:TCGTTGAAGCTG	ic:i:1	im:Z:m84094_230809_163707_s3/197988271/ccs/10314_10616	is:i:1	it:Z:TCGTTGAAGCTGATACGGTTGTAGACCT	rc:i:1	RG:Z:e4927d21	zm:i:13430463` 

It generally follows the standardized bam format but i'm facing several issues in my attempts to run SComatic with it.  

SplitBamCellTypes.py kept reporting that it was unable to identify cell barcodes and I thought maybe the expectation of a `-1` as a suffix to a cell barcode was interfering so i modified the PacBio bam file to have a -1 so in the example it is now CB:Z:ATACGGTTGTAGACCT-1 but SplitBamCellTypes still didn't work. 

Just to confirm I extracted all the cell barcodes from the bam file and intersected it with the barcodes I was providing in the --meta parameter and they did match so I'm not sure what the issue is. 

I manually separated the bam file and tried to move forward with BaseCellCounter.py but faced errors as it would create the temporary folder by cell_type but not write anything to it. So i would get a `No temporary files found`. 

How can i modify either the bam file or SComatic to work with long read data? Thank you

**Comment by Francesc-Muyas** [comment]
Dear user, 

Despite the huge interest in detecting somatic variants in single-cell long-read data, the current version of SComatic does not support this type of variant calling. I hope we can develop this upgrade in the future.

Thanks, 
Fran

**Comment by tsa4002** [comment]
Hi @Francesc-Muyas 

Thank you for the reply. I understand SComatic's limitation, which other tools also have, i was hoping more that you could elaborate on why that limitation exists. I've rephrased my question and removed the aspects of how i've tried modifying SComatic to fit that use case. 

Thanks
