### ISSUE TITLE
Why is the default value of the parameter "min_mq" 255

### ISSUE THREAD

**Issue by Topigs** [cortes-ciriano-lab/SComatic#39]
Thanks so much for such a wonderful tool！
In view the script "scripts/BaseCellCounter/BaseCellCounter py", I am very confused with the default value of the command line option "-- min_mq". Why set it to 255 instead of something more reasonable, I mean like 30.

**Comment by Francesc-Muyas** [comment]
Dear user, 
Thanks for using SComatic. This default mapping quality is ideal for detecting uniquely mapping reads in scRNA-seq data (usually aligned with STAR). 

`-- min_mq 30` would be a better parameter for DNA-based approaches like scATAC-seq.

Thanks, 
Fran
