### ISSUE TITLE
High (False)-Discoveries

### ISSUE THREAD

**Issue by Thapeachydude** [cortes-ciriano-lab/SComatic#4]
Hi Fran,

many thanks for the quick reply on the previous issue. I now ran the tool for multiple sample pools. Each pool was run independently, so barcode collisions were impossible. While some of the reported mutations make sense, I'm struggling with a (likely) high false-positive rate.
E.g. a gene is reported to be mutated in almost 100% of tumor samples, this is very unlikely given the low coverage and a reported frequency for many of them in the single digit range. Likewise, we observe mutations not called in WES data from the same samples.

Are there additional parameters you would recommend to tweak?

I ran the tool using the genome.fa file from Cellranger as reference. I included the PoN and RNA-editing files, included in this tool and only reporting "alt" for basecalling.

Cheers,
M.

**Comment by Francesc-Muyas** [comment]
Dear user,
Please find below the answer for each one of your points:

_- While some of the reported mutations make sense, I'm struggling with a (likely) high false-positive rate. E.g. a gene is reported to be mutated in almost 100% of tumor samples, but reports from literature suggest a ≈ 10% mutation frequency is more adequate._

When you speak about ~100% of samples with a gene mutated, do you speak about all samples carrying the same mutation in the same gene or different mutations in the same gene across samples? do you consider all mutations or only high-impact ones (usually, cancer analysis provide frequencies of high-impact mutations)? To further understand this question, could you also show me a few examples of these recurrent "false" variants across samples (header + lines from the out file obtained by SComatic/scripts/BaseCellCalling/BaseCellCalling.step2.py )?

_- Likewise, we observe mutations not called in WES data from the same samples._

These types of variants (scRNA-seq-specific variants) do not need to be false positive calls, as many other variables such as cancer heterogeneity, purity, and coverage in WES play an important role (check Figures 2 and 3 from the bioRxiv manuscript). Nevertheless, we can investigate what is going on in this case. Could you tell me the mean coverage achieved in the WES data? One important thing to consider here is that scRNA-seq (like 10x) usually expands regions not covered by WES approaches, so could you check (for instance opening the WES bam in IGV) if you can see reads supporting the alternative alleles for a subset of variants detected by scRNA-seq and not by your WES pipeline?

- _I'll try using a more detailed cell type annotation next, e.g. non tumor type A, non tumor type B, tumor cell type... Are there additional parameters you would recommend to tweak?_

Increasing the number of cell types helps to detect better systematic errors and germline variants. If you can increase this number would be awesome. Regarding parameters, we generated all our results with the parameters described in the [Example of how to run SComatic](https://github.com/cortes-ciriano-lab/SComatic/blob/main/docs/SComaticExample.md) section. Please, use these parameters whenever possible.

- _I ran the tool using the genome.fa file from Cellranger as reference. I included the PoN and RNA-editing files, included in this tool._

Could you confirm that this reference genome is the Hg38 version of the human genome with chromosome prefixes (chr1, chr2...)? This is crucial to be able to use both the PoN and RNA-editing files that we provided.

- Additional filters that might be helpful:

1. Create your own [Panel of Normals](https://github.com/cortes-ciriano-lab/SComatic/blob/main/docs/pon.md). This will help you to remove recurrent artefacts across samples or biases specific to your dataset. Once you run SComatic/scripts/BaseCellCalling/BaseCellCalling.step2.py with our PoN, you can re-run again this script but with your own PoN.
2. [Estimate new parameters for the Beta-Binomial distribution](https://github.com/cortes-ciriano-lab/SComatic/blob/main/docs/betabinomialestimation.md). Although our Beta-Binomial parameters were estimated with many samples, other datasets might have different background noises, so you could try to estimate new alpha and beta parameters with your data. However, this computation requires a high number of tumour-free samples.
3. Ignore variants with > 1 % population frequency in the [gnomAD](https://gnomad.broadinstitute.org/) database to remove undetected germline variants.

Cheers,
Fran
