### ISSUE TITLE
hg38 fa recommendation

### ISSUE THREAD

**Issue by malonzm1** [cortes-ciriano-lab/SComatic#42]
Hi,

Can you recommend a download source for hg38 fasta file?

Thanks and good day.

**Comment by Francesc-Muyas** [comment]
Dear user, 
We always use the Hg38 (UCSC; with prefix like chr1, chr2...). 

You can download it from here:
`https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/`

Thanks, 
Fran
