### ISSUE TITLE
Problem installing SComatic

### ISSUE THREAD

**Issue by malonzm1** [cortes-ciriano-lab/SComatic#43]
Hi,

I'm trying to install SComatic based on the installation instructions. However, I came across some errors, namely:

```
Could not solve for environment specs
Encountered problems while solving:
  - nothing provides requested numpy-groupies 0.9.14**
  - package rpy2-2.9.4-py35r341h24bf2e0_0 requires python >=3.5,<3.6.0a0, but none of the providers can be installed
```

Please advise.

Thanks.

**Comment by Francesc-Muyas** [comment]
Dear user, 
Did you manage to install the tool? 

Thanks, 
Fran

**Comment by FionaMoon** [comment]
I try to install rpy2 from conda and it works.
