### ISSUE TITLE
Does SComatic identify frameshift mutations?

### ISSUE THREAD

**Issue by FranSoriano** [cortes-ciriano-lab/SComatic#46]
Hello everyone,

To perform our analysis we would like to know if SComatic identifies **frameshift mutations**.

Thank you.

**Comment by Francesc-Muyas** [comment]
Dear user, 
Thanks for using SComatic. SComatic does not call indels, so I would not expect to find frameshift mutations. 

Thanks, 
Francesc Muyas

**Comment by FranSoriano** [comment]
Dear Fran,

Ok, that's what we thought.

Thanks.
