### ISSUE TITLE
Concurrent running of cells for step 2.

### ISSUE THREAD

**Issue by JakeJackson22** [cortes-ciriano-lab/SComatic#47]
Hi, I am a bioinformatician in the Haniffa Lab and I am trying to use SComatic to detect mutations on single cell data.

I have 122 cell types and notice that for step 2 of your example workflow you state this:

"In our experience, when running SComatic in an HPC cluster it is most efficient to compute the base count information for all cell types at once, specially when submitting each python line independently and at the same time to the cluster, and using multiple processors (p.e. --nprocs 16)"

I am using the Sanger FARM and just wondered if you had advice on how best to run SComatic for 122 cell types, as it seems to take a very long time as I am doing now, and step 2 seems to run sequentially rather than concurrently (how would I amend to code to run concurrently?).

Thank you very much

**Comment by Francesc-Muyas** [comment]
Dear user, 
How are you submitting the jobs to the FARM? 

Could you please paste the command (ideally "for" loop) for submitting the jobs to the cluster? 

Thanks, 
Fran

**Comment by JakeJackson22** [comment]
Hi Fran,

Thanks for the reply. I believe I have fixed the issue, using a pipeline developed by the Teichmann lab.

Thanks,
Jake
