### ISSUE TITLE
Matching SNP to cell barcode

### ISSUE THREAD

**Issue by malonzm1** [cortes-ciriano-lab/SComatic#57]
Hi,

Does SComatic allow matching of SNP to cell barcode?

Good day.

**Comment by Francesc-Muyas** [comment]
Dear user, 
Do you mean to match the SNVs detected by SComatic to the cell barcodes of the same sample? If so, yes. Please check this [section](https://github.com/cortes-ciriano-lab/SComatic/blob/main/docs/OtherFunctionalities.md#computing-the-genotype-for-each-cell-at-the-variant-sites).

Thanks, 
Fran
