### ISSUE TITLE
Using chromosome reference in Scomatic

### ISSUE THREAD

**Issue by Arsamat** [cortes-ciriano-lab/SComatic#62]
Hi,

I was running SComatic on single-cell data that I have. In the example, chr10 from grch38 was used as a reference.  However, if I were to also see mutations in other chromosomes would I have to rerun step 4 separately for each chromosome with its respective grch38 reference? Thank you!

**Comment by ArthurDondi** [comment]
Hi, you could run it again from step 2 with the complete hg38.fa reference (available here https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/) with `--chrom all` . 

You can also run each chromosome separately, but from step 2, not step 4 (the BaseCellCounter file is already filtered).
