### ISSUE TITLE
Get a sparse matrix after genotyping

### ISSUE THREAD

**Issue by moshl** [cortes-ciriano-lab/SComatic#7]
Hi, Fran.

After preprocessing the 10X scATAC-seq data from CRC or polyps using cellranger-atac,  I run SComatic for calling mutation following the your example. Detailly, I replaced the paremeters --max_NH and --max_nM with  the paremeter --min_mq 30 in the Step1; And I filtering the false mutations using your PON files in the Step4.  I get a sparse matrix after genotyping like the heatmap below(The color white represents the uncovered cell;  the blue represents the WT cell; the red represents the alt cell ).  Is this result correct?  Hope your advises for my analysis~

![image](https://user-images.githubusercontent.com/29252072/229062372-65c232fa-1208-40fd-97e5-bc55b9a5721e.png)

Best wishes,
Mo

**Comment by Francesc-Muyas** [comment]
Dear user, 

It is pretty hard to say with this plot whether the calls are correct (or not). However, it is important to mention that when working with scATAC or scRNA-seq data, the resulting mutation matrixes usually have many uncovered cells. In our experience, we realised that only a small fraction of the total cells (epithelial cells here) are covered by reads in the variant sites (considering both reads with and without the mutation). However, this is a limitation of the sequencing technology and the variability of coverage that we have to work with. So, this is **not** a limitation of the variant caller. 

To deal with this situation and try to do some clonality analysis, I would suggest filtering these matrixes to mutations with at least 20 mutated cells and less than 90% of uncovered cells (average values in our datasets were around ~95%). In addition, I would suggest including only cells with at least 1 mutation. 

I hope it helps.
Thanks,
Fran
