### ISSUE TITLE
Output total number of reads covering the site?

### ISSUE THREAD

**Issue by cnk113** [cortes-ciriano-lab/SComatic#8]
Hello,

I was wondering in the final step (SingleCellGenotype.py), would it be also possible to get the total number of reads covering the site (mutant or otherwise)?
The output of this would amenable with cardelino's two input matrices. 

Thanks,
Chang

**Comment by Francesc-Muyas** [comment]
Dear user, 
So far, it is not on our short-term TODO list, but we will consider it for future updates. 

Thanks,
Fran
